### ISSUE TITLE
File Open/Save Functionality

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmweb#11]
Users should be able to open existing mitmproxy dumps or save the current session as a mitmproxy dump.

**Comment by cle1000** [comment]
i have some general questions:
- For save: i will sent a request to the server to get the file, right ? not just saving the flow which is already sent and displayed to the user? 
- For open: the same i just send the file with an request to the server and the server stores this flow. but i need to set an option or something else to stop recording new flows. 
- mitmdump/ mitmproxy: with mitmproxy it is possible to save a file, but i cannot find an option to load it.

can you give me some starting point for this issuse, e.g. some links to the files where this or parts are already implemented  (like for mitmweb, and mitmdump) ?

thanks

**Comment by mhils** [comment]
- I think save should be the same as pressing `w` -> all flows in mitmproxy. It should trigger the download of the dump of all flows.
- Open should replace all flows in the state. I think this should ultimately pause proxying as well, but let's defer that for when we have that functionality.
- mitmdump/mitmproxy: You can pass `-r` :smiley:

Current implementations:
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/flow.py#L1186
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/dump.py#L133
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/flow.py#L553
