### ISSUE TITLE
mitmweb error

### ISSUE THREAD

**Issue by nerdyaddy** [mitmproxy/mitmweb#21]
I have started mitmweb as follows 
`mitmweb --wport=8181`

and access the webpage via 
`http://<ipaddress>:8181`

and get 404 Not Found when accessed via proxy.

Console prints following message:
`WARNING:tornado.access:404 GET http://stackoverflow.com/`

**Comment by mhils** [comment]
Works fine for me. mitmweb is not a supported part of mitmproxy yet, so please bear with us while we work on its usability.
