### ISSUE TITLE
Windows Commands to Start Up mitmweb in Transparent Mode

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmweb#33]
When it comes time to write up Windows documentation, here's some mitmweb start up commands to consider. I placed them in a batch file named `wmitm.bat`. You don't need to open an elevated `cmd` window as the first command elevates to `administrator` runs `windows.py` and keeps the windows open (`/K`). The second command invokes the chrome browser and opens the mitmweb UI webpage. The third command invokes `mitmweb` specifying transparent mode (`-T`) and to display domain names instead of ip address (`--host` (not yet implemented in mitmweb)).

```
powershell.exe -Command start-process -verb runas cmd {/K "C:\Python27\Lib\site-packages\mitmproxy\platform\windows.py"}

start chrome http://localhost:8081

mitmweb -T --host
```

**Comment by mhils** [comment]
Thanks for contributing this. We'll hopefully integrate that more nicely in a future release, so I'm closing this for now.
