### ISSUE TITLE
Response body edit > 100 lines

### ISSUE THREAD

**Issue by roman-bronis** [mitmproxy/mitmweb#40]
I found an issue with editing response body in mitmweb, where I can't get to lines "below" 100. Would this be fixed, or is there any workaround?

macOS X, installed with brew with mitmproxy/mitmdump

![mitmdumpbug](https://cloud.githubusercontent.com/assets/1164597/22734010/6a0429e8-edf4-11e6-8091-af8a9ab26fd5.png)

**Comment by mhils** [comment]
This seems to be a CSS error. @cle1000, any idea why we do [this](https://github.com/mitmproxy/mitmproxy/blob/2316c0fb74efefd76970c685b8f77f45834f1490/web/src/css/codemirror.less#L4)?

**Comment by roman-bronis** [comment]
@mhils You are right, locally changing:
```
.CodeMirror {
  border: 1px solid #ccc;
  height: auto !important;
  /*max-height: 2048px !important;*/
}
```
fixed the issue.

I'm more than happy with this workaround, but I think this project also deserves proper fix. ;)

Thank you for your good work and fast response! Appreciated!

**Comment by cle1000** [comment]
@mhils sorry i have no idea anymore why I add this line of code. I will check it in the evening

**Comment by cle1000** [comment]
@mhils I added the max-height to add scrollbars to the codeeditor window 

![screenshot - 2017-02-08 - 14 13 07](https://cloud.githubusercontent.com/assets/5902525/22738722/d747e26a-ee08-11e6-934c-bc68cfe7bba3.png)

but i think it is not really necessary,...

**Comment by mhils** [comment]
Hmm - Could it be possible that we did that for performance reasons?
Otherwise let's ditch this entirely. :)

Clemens Brunner <notifications@github.com> schrieb am Mi., 8. Feb. 2017,
14:16:
