### ISSUE TITLE
Relative paths for resources (js, css, images, websockets, etc).

### ISSUE THREAD

**Issue by Stas404** [mitmproxy/mitmweb#47]
Hi. Relative paths is needed for access to mitmweb panel via custom nested url.
Say,  https://example.com/some/path/to/mitmweb-panel/
Nginx upstream configuration for example:
```
upstream mitm  {
  server 127.0.0.1:8081 fail_timeout=0;
}

  location /some/path/to/mitmweb-panel/ {
    # can be protected (basic auth etc.)
    proxy_pass http://mitm/;
    proxy_redirect off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

**Comment by Kriechi** [comment]
This repository and issue tracker is / was only used to track the GSoC progress.
Please open an new issue in the main mitmproxy repository: https://github.com/mitmproxy/mitmproxy/issues/new
