### ISSUE TITLE
Basic Options Screen

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmweb#5]
We want an equivalent of pressing `o` in mitmproxy. In the first iteration, we should expose the important binary options:
- `--host` 
- `--no-upstream-cert`
- `--raw-tcp`
- `--http2`
- `--anticache`
- `--anticomp`
- `--stickycookie`
- `--stickyauth`
- `--stream`

There are more, but these are the most important ones IMO.

**Comment by cle1000** [comment]
Question to options:
- `--host`: how i can change this ? 
- `--no-upstream-cert`: server.config just toggle 
- `--raw-tcp`: how i can change this ? 
- `--http2`: how i can change this ? 
- `--anticache`: is clear just toggle 
- `--anticomp`: is clear just toggle 
- `--stickycookie`: i need a textfield on the client side for the input
- `--stickyauth`:  i need a textfield on the client side for the input
- `--stream`: how i can change this ?

**Comment by mhils** [comment]
This is our main option processing: https://github.com/mitmproxy/mitmproxy/blob/79cb17ef03afac2b7314f6aed13480024672993e/mitmproxy/main.py#L113-L120

All the bare command line switches are defined here: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/cmdline.py 

Options specific to the proxy server are handled here:
https://github.com/mitmproxy/mitmproxy/blob/79cb17ef03afac2b7314f6aed13480024672993e/mitmproxy/proxy/config.py

All options specific to mitmweb are specified here:
https://github.com/mitmproxy/mitmproxy/blob/79cb17ef03afac2b7314f6aed13480024672993e/mitmproxy/web/__init__.py#L89

If you follow this trail, you should see that `--host` matches to the `options.showhost`. Similarly, `--raw-tcp` matches to `server.config.rawtcp`. Makes sense?

Let's do all boolean options first and `--sticky*` and `--stream` later on.

**Comment by cle1000** [comment]
yes this makes sense, thanks for your quick response :)
