### ISSUE TITLE
UI Concept

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmweb#7]
@gzzhanghao remarked that he is not quite satisfied with the current UI and he would like to simplify the top menu. Here's his very early mockup:

![image](https://cloud.githubusercontent.com/assets/1019198/14770450/d8306484-0a26-11e6-838d-bf0568510a6a.png)

I agree that it's currently a lot of wasted space, but we have lots of stuff to fill it. I'll make a more concrete proposal in the next days and we should meet somewhere in the middle. :smiley:

**Comment by mhils** [comment]
Here's a quick sketch of my UI proposal, which is largely inspired by the Microsoft Office Ribbon UI. Let me first sketch the goals this should accomplish:
- **Ease of Use:** One major complaint I get about mitmproxy is that the initial learning curve (installing, setup, ..) is apparently steep. We need to change that!
- **Discovereability of Features:** I gave a few talks to somewhat regular mitmproxy users, and most were actually unaware that we support stuff such as Server Replay.
- **Extensibility:** One of mitmproxy's strengths are inline scripts, which make everything customizable. Ultimately, it'd be great if they can hook into some parts of the UI as well.

At the top, we have a few categories that group all actions/options:
- **Start**: The main category. Start/Stop recording, filters, interception, ...
- **Proxy**: A menu where you can configure the proxy mode, port, etc.
- **Replay**: You can enable client/server replay here and set server replay options
- **Report**: Clicking here replaces the main ui below with the report editor (
- **Options**: The mitmweb counterpart to [mitmproxy's option screen](https://maximilianhils.com/upload/2016-05/2016-05-03_14-40-09.png).
- **XXX**: The very nice part about this structure is that an extension could just hook into that and add its own tab.

![image](https://cloud.githubusercontent.com/assets/1019198/14998702/0646d35c-113a-11e6-8f72-7b816f732412.png)

Clicking on mitmproxy opens the File menu (as with Office):

![image](https://cloud.githubusercontent.com/assets/1019198/14999042/a929b476-113b-11e6-8c8b-1d04228594ed.png)

Once you select a Flow, a new Ribbon Tab appears for flow editing and other flow-specific actions.

![image](https://cloud.githubusercontent.com/assets/1019198/14998876/d5ce8fac-113a-11e6-81c8-f8c48b7e9acb.png)

The idea is that this opens automaticall, just as Office does it:

![image](https://maximilianhils.com/upload/2016-05/2016-05-03_14-46-14.gif)

I hope this somehow conveys the idea of what I'd like to build.

@mitmproxy/mitmweb, what are your thoughts on this?

**Comment by cortesi** [comment]
I like this. Some rough thoughts:
- For some menu items (e.g. Options) quite a bit of vertical space will be required. We might want to think of a different nav paradigm there - a modal or total-page switch. The ribbon idea is only pleasant if the height of the ribbon stays constant, and I wonder about the usability of a scroll area within the ribbon body.
- We may also want a show/hide ribbon button in the far right.

**Comment by cle1000** [comment]
I also like this mockup and I also agree to @cortesi to implement a show/hide ribbon button. @mhils: You want that the ribbon opens automatically (good idea), but this will affect just the "flow" tab. I don't know when the other tabs should be open automatically.

**Comment by mhils** [comment]
@cle1000: Yes - generally speaking, this affects tabs which are only visible in a specific context. For now, this is just the flow tab.

@cortesi: Yes, the ribbon should be fixed-height. For the options form, a total-page switch should do just fine, but we can defer that until we have too many options.

@gzzhanghao, thoughts?
