### ISSUE TITLE
Flow Editing

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmweb#8]
A users should be able to edit flows in an intuitive way. What we currently miss:
1. It is not obvious that you can edit the URL or the header by just clicking on it. 
2. We need a good approach for a body editor (see design challenge)
3. Some parts are broken (e.g. editing the HTTP version)

**Comment by mhils** [comment]
Possibly relevant: https://github.com/Microsoft/monaco-editor

**Comment by cle1000** [comment]
So my plan for this task:
- start with the 2. part and finish with part 1 and 3 

part 2:
- implement an editing function, like for the headers
- add monaco editor as a own react component
- change json and raw view mode to monaco editing mode
- add a new file mode, called FileView (just a field, with name, extension and filesize)
- add a upload button to replace the body
- ?? add more different modes, like html, javascript,... ? or just one raw mode where we support different languages ?

**Comment by cle1000** [comment]
part 3:
Some parts are broken (e.g. editing the HTTP version):
how can i test if this is working, or not ?
i think i also found different bug, if you modify headers, and change a flow then you get sometimes the values from the previous selected flow

**Comment by mhils** [comment]
> ?? add more different modes, like html, javascript,... ? or just one raw mode where we support different languages ?

This is #13 - we should re-use our Python stuff. :-)

**Comment by mhils** [comment]
> Some parts are broken (e.g. editing the HTTP version):
> how can i test if this is working, or not ?

If the UI updates properly (immediately and after refresh) and replay works, everything should be fine.
